name: kitlang
version: '0.1.0'
author: Ben Morris <ben@bendmorris.com>
license: LGPL
license-file: LICENSE.md
dependencies:
- base >=4.7
default-extensions:
- OverloadedStrings

library:
  source-dirs:
  - bin
  - src
  ghc-options: -O2
  build-tools:
  - alex
  - happy
  exposed-modules:
  - Kit
  - Kit.Ast
  - Kit.CodeGen.C
  - Kit.Compiler
  - Kit.Error
  - Kit.HashTable
  - Kit.Log
  - Kit.Parser
  - Kit.Str
  dependencies:
  - ansi-terminal
  - array
  - bytestring
  - directory
  - filepath
  - hashable
  - hashtables
  - language-c
  - pretty
  - text
  - time
  - transformers

executables:
  kitc:
    main: Main.hs
    source-dirs: bin/kitc
    ghc-options: -O2
    dependencies:
    - ansi-terminal
    - kitlang
    - optparse-applicative ==0.14.2.0
    - time

  kit:
    main: Main.hs
    source-dirs: bin/kit
    ghc-options: -O2
    dependencies:
    - ansi-terminal
    - optparse-applicative ==0.14.2.0

tests:
  unit-tests:
    main: Test.hs
    source-dirs: tests
    build-tools:
    - alex
    - happy
    dependencies:
    - directory
    - filepath
    - hspec
    - kitlang
    - language-c
    - pretty
    - QuickCheck
